{
 "title": "Kong AI Gateway Dashboard (Offical)",
 "description": "Kong AI Gateway Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total,instance)"
    }
   },
   {
    "name": "ai_provider",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,ai_provider)"
    }
   },
   {
    "name": "ai_model",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,ai_model)"
    }
   },
   {
    "name": "embeddings_provider",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,embeddings_provider)"
    }
   },
   {
    "name": "embeddings_model",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,embeddings_model)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,consumer)"
    }
   },
   {
    "name": "token_type",
    "query": {
     "query": "label_values(kong_ai_llm_tokens_total,token_type)"
    }
   },
   {
    "name": "mcp_tool",
    "query": {
     "query": "label_values(kong_ai_mcp_latency_ms_count,tool_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total MCP Request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_latency_ms_count{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~'$instance', method!=\"\", tool_name!=\"\"}[$__rate_interval])) by (le, tool_name)\n)",
     "legendFormat": "{{ tool_name }}"
    }
   ]
  },
  {
   "title": "MCP Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_latency_ms_count{instance=~\"$instance\"}[$__range])) by (tool_name)",
     "legendFormat": "{{tool_name}}"
    }
   ]
  },
  {
   "title": "MCP Errors Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_error_total{instance=~\"$instance\"}[1m])) by (tool_name, type)",
     "legendFormat": "{{tool_name}}--{{type}}"
    }
   ]
  },
  {
   "title": "MCP Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_mcp_latency_ms_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "MCP RPS Per Tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_mcp_latency_ms_count{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (tool_name)",
     "legendFormat": "{{tool_name}} Total RPS"
    }
   ]
  },
  {
   "title": "MCP RPS Per Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_mcp_latency_ms_count{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (tool_name, method)",
     "legendFormat": "{{ tool_name }}-{{ method  }}  RPS"
    }
   ]
  },
  {
   "title": "MCP Total Error Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_error_total{instance=~\"$instance\"}[1m])) by (type) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "MCP Error Code Per Tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_error_total{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (tool_name, type) ",
     "legendFormat": "{{ tool_name  }} -- {{type}}"
    }
   ]
  },
  {
   "title": "MCP Error Code Per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kong_ai_mcp_error_total{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (tool_name, type, method) ",
     "legendFormat": "{{ tool_name }} --{{ method  }} -- {{type}} "
    }
   ]
  },
  {
   "title": "MCP Lantency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "MCP Lantency Per Tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\",  tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P90-{{ tool_name }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\",  tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P95-{{ tool_name }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\",  tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P99-{{ tool_name }}"
    }
   ]
  },
  {
   "title": "MCP Lantency Per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\",  tool_name=~\"$mcp_tool\"}[1m])) by (le, method, tool_name))",
     "legendFormat": "P90-{{tool_name}} - {{ method }} "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\",  tool_name=~\"$mcp_tool\"}[1m])) by (le, method, tool_name))",
     "legendFormat": "P90-{{tool_name}} - {{ method }} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_latency_ms_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, method, tool_name))",
     "legendFormat": "P99-{{tool_name}} - {{ method }} "
    }
   ]
  },
  {
   "title": "MCP Response Body Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "MCP Response Body Size Per Tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P90 - {{tool_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P95 - {{tool_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name))",
     "legendFormat": "P99 - {{tool_name}}"
    }
   ]
  },
  {
   "title": "MCP Response Body Size Per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name, method))",
     "legendFormat": "P90- {{tool_name}} - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name, method))",
     "legendFormat": "P95- {{tool_name}} - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_mcp_response_body_size_bytes_bucket{instance=~\"$instance\", tool_name=~\"$mcp_tool\"}[1m])) by (le, tool_name, method))",
     "legendFormat": "P99- {{tool_name}} - {{ method }}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per second (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_requests_total{instance=~\"$instance\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS per AI Provider",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_requests_total{ instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (ai_provider)",
       "legendFormat": "{{ ai_provider }}"
      }
     ]
    },
    {
     "title": "RPS per AI Model",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_requests_total{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (ai_model)",
       "legendFormat": "{{ ai_model }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Token Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token per second (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_tokens_total{instance=~\"$instance\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TPS per AI Provider",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_tokens_total{ instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (ai_provider)",
       "legendFormat": "{{ ai_provider }}"
      }
     ]
    },
    {
     "title": "RPS per AI Model",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(rate(kong_ai_llm_tokens_total{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (ai_model)",
       "legendFormat": "{{ ai_model }}"
      }
     ]
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "LLM Provider Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "LLM Provider Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P90-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P95-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P99-{{ ai_provider }}"
    }
   ]
  },
  {
   "title": "LLM Provider Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P90-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P95-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P99-{{ ai_model }}"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P90-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P95-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P99-{{ ai_provider }}"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P90-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P95-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P99-{{ ai_model }}"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency per Embeddings Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P90-{{ embeddings_provider }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P95-{{ embeddings_provider }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P99-{{ embeddings_provider }}"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P90-{{ embeddings_model }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P95-{{ embeddings_model }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P99-{{ embeddings_model }}"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P90-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P95-{{ ai_provider }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m])) by (le, ai_provider))",
     "legendFormat": "P99-{{ ai_provider }}"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P90-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P95-{{ ai_model }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m])) by (le, ai_model))",
     "legendFormat": "P99-{{ ai_model }}"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=~\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P90-{{ embeddings_provider }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=~\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P95-{{ embeddings_provider }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=~\"$embeddings_provider\"}[1m])) by (le, embeddings_provider))",
     "legendFormat": "P99-{{ embeddings_provider }}"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P90-{{ embeddings_model }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P95-{{ embeddings_model }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le, embeddings_model))",
     "legendFormat": "P99-{{ embeddings_model }}"
    }
   ]
  },
  {
   "title": "Costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_cost_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cost Total per Consumer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_cost_total{instance=~\"$instance\", consumer=~\"$consumer\"}) by (consumer)",
       "legendFormat": "{{ consumer }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Token Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Token Total per AI Provider",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", ai_provider=~\"$ai_provider\"}) by (ai_provider)",
       "legendFormat": "{{ ai_provider }}"
      }
     ]
    },
    {
     "title": "Token Total per AI Model",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 101 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", ai_model=~\"$ai_model\"}) by (ai_model)",
       "legendFormat": "{{ ai_model }}"
      }
     ]
    },
    {
     "title": "Token Total per Token Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", token_type=~\"$token_type\"}) by (token_type)",
       "legendFormat": "{{ token_type }}"
      }
     ]
    },
    {
     "title": "Token Total per Consumer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", consumer=~\"$consumer\"}) by (consumer)",
       "legendFormat": "{{ consumer }}"
      }
     ]
    }
   ]
  }
 ]
}