receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  filter/traces:
    error_mode: ignore
    traces:
      span:
        - 'name == "ipc.connect"'
        - 'name == "tcp.connect"'
        - 'name == "prisma:client:load_engine"'
        - 'name == "prisma:client:detect_platform"'
        - 'attributes["url.path"] == "/health"'
        - 'attributes["http.target"] == "/health"'
        - 'attributes["http.target"] == "/"'
        - 'attributes["api_kind"] == "heartbeat"'
        - 'attributes["api_kind"] == "list_offsets"'
        - 'attributes["api_kind"] == "offset_fetch"'
        - 'attributes["api_kind"] == "metadata"'
        - 'attributes["api_kind"] == "sync_group"'
        - 'attributes["api_kind"] == "join_group"'
        - 'attributes["api_kind"] == "find_coordinator"'
        - 'attributes["api_kind"] == "APIVersion(6)"'

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: 0.0.0.0:8889
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/traces, batch]
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
