name: Sync Konnect setting using kongctl

on:
  push:
    paths:
      - kongctl/*.yaml
      - .github/workflows/kongctl.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup kongctl
        uses: kong/setup-kongctl@659d5c2b0f4db2e25d63797035358a22907421db # v1.0.0
        with:
          kongctl-version: 1.2.1
      - name: Plan Konnect settings
        run: |
          kongctl plan \
            -f kongctl \
            --pat ${{ secrets.KONNECT_TOKEN }}
      - name: Sync Konnect settings
        run: |
          kongctl sync \
            -f kongctl \
            --pat ${{ secrets.KONNECT_TOKEN }} \
            --auto-approve
